# Generated by Django 3.2 on 2021-04-25 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=100)),
                ('position_url', models.URLField(max_length=300, null=True)),
                ('date_opened', models.DateField(null=True)),
                ('date_closed', models.DateField(blank=True, default='', null=True)),
                ('skills', models.CharField(choices=[('java', 'Java'), ('c++', 'C++'), ('algorithm', 'Algorithm Design'), ('object', 'Object Oriented'), ('kubernetes', 'Kubernetes')], max_length=100)),
                ('job_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('careers_url', models.URLField(max_length=300, null=True)),
                ('industry', models.CharField(choices=[('tech', 'Tech'), ('ecommerce', 'Ecommerce'), ('healthcare', 'Healthcare'), ('pharma', 'Pharmaceutical'), ('aerospace', 'Aerospace'), ('fintech', 'FinTech'), ('nonprofit', 'Nonprofit'), ('defense', 'Defense'), ('other', 'Other')], max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
