# Generated by Django 3.2 on 2021-04-20 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='position',
            name='skills',
            field=models.CharField(choices=[('java', 'Java'), ('c++', 'C++'), ('algorithm', 'Algorithm Design'), ('object', 'Object Oriented'), ('kubernetes', 'Kubernetes')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
