# Generated by Django 3.2 on 2021-04-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210425_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='skills',
            field=models.CharField(choices=[('Java', 'Java'), ('C++', 'C++'), ('Algorithm Design', 'Algorithm Design'), ('Object Oriented', 'Object Oriented'), ('Kubernetes', 'Kubernetes')], max_length=100),
        ),
    ]
