# Generated by Django 3.2 on 2021-05-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20210502_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communication',
            old_name='data',
            new_name='date',
        ),
    ]
