# Generated by Django 3.2 on 2021-05-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_rename_data_communication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='careers_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('tech', 'Tech'), ('ecommerce', 'Ecommerce'), ('healthcare', 'Healthcare'), ('pharma', 'Pharmaceutical'), ('aerospace', 'Aerospace'), ('fintech', 'FinTech'), ('nonprofit', 'Nonprofit'), ('defense', 'Defense'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
