# Generated by Django 3.2.3 on 2021-05-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20210523_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ManyToManyField(to='jobs.Skill'),
        ),
    ]
