# Generated by Django 3.2.3 on 2021-05-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20210523_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('tech', 'Tech'), ('ecommerce', 'Ecommerce'), ('healthcare', 'Healthcare'), ('pharma', 'Pharmaceutical'), ('aerospace', 'Aerospace'), ('fintech', 'FinTech'), ('nonprofit', 'Nonprofit'), ('defense', 'Defense'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
