# Generated by Django 3.2.3 on 2021-05-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('jobs', '0013_auto_20210527_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.document'),
        ),
        migrations.AlterField(
            model_name='position',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jobs.Skill'),
        ),
    ]
